_base_:
  - ../../datamodules/on-the-fly-stem-tv-profiles.yaml
  - ${base_config_path}/train_base.yaml

seed: 2026

sr: 44100
n_fft: 2048
hop_length: 512

n_src: 3
n_chan: 1

sfc_npu_n_bands: 64
sfc_npu_d_inner: 64
sfc_npu_d_model: 160
sfc_npu_n_separator_layers: 8
sfc_npu_time_kernel_size: 2
sfc_npu_freq_kernel_size: 3
sfc_npu_ffn_expansion: 4
sfc_npu_dilation_cycle: [1]
sfc_npu_masking: true
sfc_npu_use_learnable_query: true

trainer:
  max_epochs: 150
  check_val_every_n_epoch: 1
  gradient_clip_val: 5.0
  sync_batchnorm: True
  deterministic: false
  limit_train_batches: 1354
  limit_val_batches: 10
  benchmark: True
  use_distributed_sampler: False
  precision: bf16-mixed
  callbacks:
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      filename: "{epoch:04d}"
      save_top_k: 5
      monitor: validation/loss
      mode: min
      save_last: True
    - _target_: lightning.pytorch.callbacks.RichProgressBar
      refresh_rate: 5
    - _target_: lightning.pytorch.callbacks.RichModelSummary
      max_depth: 3

task:
  _target_: spectral_feature_compression.core.tasks.sup_task.SupTask
  n_fft: ${n_fft}
  hop_length: ${hop_length}
  css_validation: true
  ema_weight: null
  ema_update_freq: null
  model:
    _target_: spectral_feature_compression.core.model.sfc_small_conv2d_bn_npu.build_sfc_small_conv2d_bn_npu_system
    n_fft: ${n_fft}
    hop_length: ${hop_length}
    fs: ${sr}
    scaling: false
    css_segment_size: 12
    css_shift_size: 6
    n_src: ${n_src}
    n_chan: ${n_chan}
    n_bands: ${sfc_npu_n_bands}
    d_inner: ${sfc_npu_d_inner}
    d_model: ${sfc_npu_d_model}
    n_separator_layers: ${sfc_npu_n_separator_layers}
    time_kernel_size: ${sfc_npu_time_kernel_size}
    freq_kernel_size: ${sfc_npu_freq_kernel_size}
    ffn_expansion: ${sfc_npu_ffn_expansion}
    dilation_cycle: ${sfc_npu_dilation_cycle}
    masking: ${sfc_npu_masking}
    use_learnable_query: ${sfc_npu_use_learnable_query}
  loss:
    _target_: spectral_feature_compression.core.loss.snr.ThresSNRLossWithInactiveSource
    solve_perm: false
    n_src: ${n_src}
    zeroref_weight: 0.1
    only_denominator: false
  optimizer_config:
    _target_: aiaccel.torch.lightning.OptimizerConfig
    optimizer_generator:
      _partial_: True
      _target_: torch.optim.AdamW
      lr: 1.e-3
      weight_decay: 1.e-2
      betas: [0.9, 0.999]
    scheduler_generator:
      _partial_: True
      _target_: spectral_feature_compression.common.lr_schedulers.warmup.WarmUpStepLR
      warmup_steps: 5000
      decay_start_step: 101550
      decay_stop_step: 203100
      step_size: 1354
      decay: 0.96
    scheduler_interval: step
