"""Factory entry points for the 2026 edge-separation proposal set.

The research notes point to several repo-local implementation tracks.  This file
keeps them as thin, explicit builders over existing model families so configs
can select the proposal by name without silently changing older recipes.
"""

from __future__ import annotations

from collections.abc import Sequence

from BandSFCNetNPU.training_wrapper import build_band_sfc_net_npu_system
from EdgeFusionNPU.training_wrapper import build_edge_fusion_npu_system
from spectral_feature_compression.core.model import tvconv_pyramid_npu_separator_2d as _tvconv_pyramid_npu_separator_2d
from spectral_feature_compression.core.model.adaptive_mel_locoformer_lite_sfc_2d import (
    build_adaptive_mel_locoformer_lite_sfc_system as _build_adaptive_mel_locoformer_lite_sfc_system,
)
from spectral_feature_compression.core.model.adaptive_mel_sfc_2d import (
    build_adaptive_mel_sfc_system as _build_adaptive_mel_sfc_system,
)
from spectral_feature_compression.core.model.bslocoformer import BSLocoformer
from spectral_feature_compression.core.model.crossattn_enc_dec import CrossAttnDecoder, CrossAttnEncoder
from spectral_feature_compression.core.model.foa_event_query_prompted_sfc import (
    build_foa_event_query_prompted_asymmetric_sfc_system as _build_foa_event_query_prompted_asymmetric_sfc_system,
)
from spectral_feature_compression.core.model.model_wrapper import ModelWrapper
from spectral_feature_compression.core.model.online_hierarchical_soft_band_parallel_ffi_sfc_2d import (
    build_online_hierarchical_soft_band_parallel_ffi_sfc_system,
)
from spectral_feature_compression.core.model.prompted_asymmetric_sfc_2d import (
    build_prompted_asymmetric_sfc_system as _build_prompted_asymmetric_sfc_system,
)
from spectral_feature_compression.core.model.residual_refinement_sfc_2d import (
    build_residual_refinement_sfc_system as _build_residual_refinement_sfc_system,
)
from spectral_feature_compression.core.model.sfc_locoformer_conv2d_32b_npu import (
    build_sfc_locoformer_conv2d_32b_npu_system as _build_sfc_locoformer_conv2d_32b_npu_system,
)
from spectral_feature_compression.core.model.source_aware_melband_loco_cnb_student_sfc_2d import (
    build_source_aware_melband_loco_cnb_student_sfc_system as _build_source_aware_melband_loco_cnb_student_sfc_system,
)
from spectral_feature_compression.core.model.source_aware_melband_roformer import (
    build_source_aware_melband_roformer_system as _build_source_aware_melband_roformer_system,
)
from spectral_feature_compression.core.model.source_aware_melband_strong_student_sfc_2d import (
    build_source_aware_melband_strong_student_sfc_system as _build_source_aware_melband_strong_student_sfc_system,
)
from spectral_feature_compression.core.model.source_aware_melband_student_sfc_2d import (
    build_source_aware_melband_student_sfc_system as _build_source_aware_melband_student_sfc_system,
)
from spectral_feature_compression.core.model.source_aware_residual_sfc_2d import (
    build_source_aware_residual_sfc_system as _build_source_aware_residual_sfc_system,
)
from spectral_feature_compression.core.model.source_aware_sfc_locoformer_teacher import (
    build_source_aware_sfc_locoformer_teacher_system as _build_source_aware_sfc_locoformer_teacher_system,
)
from spectral_feature_compression.core.model.source_split_sfc_2d import (
    build_source_split_sfc_system as _build_source_split_sfc_system,
)
from spectral_feature_compression.core.model.sparse_unet_mel_sfc_2d import (
    build_sparse_unet_mel_sfc_system as _build_sparse_unet_mel_sfc_system,
)
from spectral_feature_compression.core.model.tvconv_pyramid_npu_separator_2d import (
    build_tvconv_pyramid_convgru_npu_separator_system as _build_tvconv_pyramid_convgru_npu_separator_system,
)
from spectral_feature_compression.core.model.tvconv_pyramid_npu_separator_2d import (
    build_tvconv_pyramid_convlstm_npu_separator_system as _build_tvconv_pyramid_convlstm_npu_separator_system,
)
from spectral_feature_compression.core.model.tvconv_pyramid_npu_separator_2d import (
    build_tvconv_pyramid_npu_separator_system as _build_tvconv_pyramid_npu_separator_system,
)
from spectral_feature_compression.core.model.tvconv_pyramid_npu_separator_2d import (
    build_tvconv_pyramid_sfclite_query_npu_separator_system as _build_tvconv_pyramid_sfclite_query_npu_separator_system,
)

build_source_aware_sfc_locoformer_teacher_system = _build_source_aware_sfc_locoformer_teacher_system
build_tvconv_pyramid_npu_separator_system = _build_tvconv_pyramid_npu_separator_system
build_tvconv_pyramid_convgru_npu_separator_system = _build_tvconv_pyramid_convgru_npu_separator_system
build_tvconv_pyramid_convlstm_npu_separator_system = _build_tvconv_pyramid_convlstm_npu_separator_system
build_tvconv_pyramid_sfclite_query_npu_separator_system = _build_tvconv_pyramid_sfclite_query_npu_separator_system
build_tvconv_pyramid_sourceaware_sfclite_convgru_npu_separator_system = (
    _tvconv_pyramid_npu_separator_2d.build_tvconv_pyramid_sourceaware_sfclite_convgru_npu_separator_system
)


def build_sfc_locoformer_lite_plus_system(
    *,
    n_fft: int,
    hop_length: int,
    fs: int,
    n_src: int = 4,
    n_chan: int = 2,
    n_bands: int = 64,
    band_config: str = "musical",
    query_type: str = "learnable",
    d_inner: int = 64,
    d_model: int = 96,
    n_layers: int = 4,
    n_heads: int = 4,
    encoder_heads: int | None = None,
    attention_dim: int | None = None,
    ffn_type: str | Sequence[str] = ("swiglu_conv1d", "swiglu_conv1d"),
    ffn_hidden_dim: int | Sequence[int] | None = None,
    conv1d_kernel: int = 8,
    conv1d_shift: int = 1,
    num_groups: int = 4,
    dropout: float = 0.1,
    flash_attention: bool = True,
    masking: bool = True,
    scaling: bool = True,
    css_segment_size: int = 12,
    css_shift_size: int = 6,
    css_batch_size: int = 1,
    checkpointing: bool = False,
) -> ModelWrapper:
    """Proposal A: SFC-CA encoder/decoder with a compact TF-Locoformer core."""

    attention_dim = d_model if attention_dim is None else attention_dim
    encoder_heads = n_heads if encoder_heads is None else encoder_heads
    ffn_type_arg: str | Sequence[str]
    if isinstance(ffn_type, str):
        ffn_type_arg = [ffn_type]
        ffn_hidden_dim = [2 * d_model] if ffn_hidden_dim is None else ffn_hidden_dim
        if isinstance(ffn_hidden_dim, int):
            ffn_hidden_dim = [ffn_hidden_dim]
    else:
        ffn_type_arg = ffn_type
        ffn_hidden_dim = tuple(2 * d_model for _ in ffn_type_arg) if ffn_hidden_dim is None else ffn_hidden_dim
        if isinstance(ffn_hidden_dim, int):
            ffn_hidden_dim = tuple(ffn_hidden_dim for _ in ffn_type_arg)
    encoder = CrossAttnEncoder(
        d_inner=d_inner,
        d_model=d_model,
        n_chan=n_chan,
        sample_rate=fs,
        n_fft=n_fft,
        n_bands=n_bands,
        band_config=band_config,
        query_type=query_type,
        n_heads=encoder_heads,
        slope=[1] * encoder_heads,
        learnable_slope=False,
        learnable_pos_bias=True,
        mask_outside_bands=False,
    )
    decoder = CrossAttnDecoder(
        d_inner=d_inner,
        d_model=d_model,
        n_src=n_src,
        n_chan=n_chan,
        sample_rate=fs,
        n_fft=n_fft,
        n_bands=n_bands,
        band_config=band_config,
        query_type=query_type,
        n_heads=encoder_heads,
        slope=[1] * encoder_heads,
        learnable_slope=False,
        learnable_pos_bias=True,
        mask_outside_bands=False,
    )
    model = BSLocoformer(
        encoder=encoder,
        decoder=decoder,
        n_src=n_src,
        n_chan=n_chan,
        n_layers=n_layers,
        emb_dim=d_model,
        norm_type="rmsgroupnorm",
        num_groups=num_groups,
        tf_order="ft",
        n_heads=n_heads,
        flash_attention=flash_attention,
        attention_dim=attention_dim,
        ffn_type=ffn_type_arg,
        ffn_hidden_dim=ffn_hidden_dim,
        conv1d_kernel=conv1d_kernel,
        conv1d_shift=conv1d_shift,
        dropout=dropout,
        masking=masking,
        checkpointing=checkpointing,
    )
    return ModelWrapper(
        model=model,
        n_fft=n_fft,
        hop_length=hop_length,
        fs=fs,
        scaling=scaling,
        css_segment_size=css_segment_size,
        css_shift_size=css_shift_size,
        css_batch_size=css_batch_size,
    )


def build_band_sfc_net_rt_plus_system(
    *,
    n_fft: int,
    hop_length: int,
    fs: int,
    n_src: int = 3,
    n_chan: int = 1,
    scaling: bool = False,
    freq_preprocess_enabled: bool = True,
    freq_preprocess_keep_bins: int | None = 475,
    freq_preprocess_target_bins: int | None = 512,
    freq_preprocess_mode: str = "triangular",
    dc_bypass_enabled: bool = False,
    dc_policy: str = "zero",
    pcen_preprocess_enabled: bool = False,
    pcen_smooth_coef: float = 0.98,
    pcen_alpha: float = 0.5,
    pcen_delta: float = 2.0,
    pcen_root: float = 0.5,
    pcen_eps: float = 1e-6,
    pcen_gain_floor: float = 0.05,
    pcen_gain_ceiling: float = 20.0,
    css_segment_size: int = 12,
    css_shift_size: int = 6,
    css_batch_size: int = 1,
):
    """Proposal B: BandSFCNet-RT+ edge student with residual correction head."""

    return build_band_sfc_net_npu_system(
        n_fft=n_fft,
        hop_length=hop_length,
        fs=fs,
        n_src=n_src,
        n_chan=n_chan,
        preset="rt_plus",
        scaling=scaling,
        freq_preprocess_enabled=freq_preprocess_enabled,
        freq_preprocess_keep_bins=freq_preprocess_keep_bins,
        freq_preprocess_target_bins=freq_preprocess_target_bins,
        freq_preprocess_mode=freq_preprocess_mode,
        dc_bypass_enabled=dc_bypass_enabled,
        dc_policy=dc_policy,
        pcen_preprocess_enabled=pcen_preprocess_enabled,
        pcen_smooth_coef=pcen_smooth_coef,
        pcen_alpha=pcen_alpha,
        pcen_delta=pcen_delta,
        pcen_root=pcen_root,
        pcen_eps=pcen_eps,
        pcen_gain_floor=pcen_gain_floor,
        pcen_gain_ceiling=pcen_gain_ceiling,
        css_segment_size=css_segment_size,
        css_shift_size=css_shift_size,
        css_batch_size=css_batch_size,
    )


def build_adaptive_mel_loco_cnb_npu_system(
    *,
    n_fft: int,
    hop_length: int,
    fs: int,
    n_src: int = 3,
    n_chan: int = 1,
    preset: str = "adaptive_mel_loco_cnb_soft_band_query",
    transport: str | None = None,
    query_type: str = "adaptive",
    n_bands: int | None = None,
    channels: int | None = None,
    num_stages: int | None = None,
    time_kernel: int | None = None,
    freq_kernel: int | None = None,
    dilation_cycle: Sequence[int] | None = None,
    routing_normalization: str | None = None,
    use_attn: bool | None = None,
    attn_window: int | None = None,
    num_heads: int | None = None,
    head_dim: int | None = None,
    pooled_mixer_hidden: int | None = None,
    pooled_mixer_hidden_schedule: Sequence[int] | None = None,
    encoder_capacity_mixer_hidden: int | None = None,
    encoder_capacity_mixer_layers: int | None = None,
    decoder_capacity_mixer_hidden: int | None = None,
    decoder_capacity_mixer_layers: int | None = None,
    stage_type: str | None = None,
    cnb_kernel: int | None = None,
    cnb_dilation_schedule: Sequence[int] | None = None,
    band_spec_type: str | None = None,
    low_freq_hz: float | None = None,
    low_freq_band_fraction: float | None = None,
    overlap_factor: float | None = None,
    low_freq_overlap_factor: float | None = None,
    bin_frequencies_hz=None,
    loco_expansion: int | None = None,
    loco_ffn_expansion: int | None = None,
    loco_time_kernel: int | None = None,
    loco_band_kernel: int | None = None,
    loco_time_dilation: int | None = None,
    residual_head: bool | None = None,
    scaling: bool = False,
    freq_preprocess_enabled: bool = True,
    freq_preprocess_keep_bins: int | None = 475,
    freq_preprocess_target_bins: int | None = 512,
    freq_preprocess_mode: str = "triangular",
    dc_bypass_enabled: bool = False,
    dc_policy: str = "zero",
    pcen_preprocess_enabled: bool = False,
    pcen_smooth_coef: float = 0.98,
    pcen_alpha: float = 0.5,
    pcen_delta: float = 2.0,
    pcen_root: float = 0.5,
    pcen_eps: float = 1e-6,
    pcen_gain_floor: float = 0.05,
    pcen_gain_ceiling: float = 20.0,
    css_segment_size: int = 12,
    css_shift_size: int = 6,
    css_batch_size: int = 1,
):
    """Strong strict-NPU student: adaptive-mel SFC + Loco-CNB.

    This is the production-minded follow-up to the earlier balanced CNB branch:
    it improves features before compression, uses overlapped mel bands, adds
    local TF modeling around the FSMN/CNB core, and strengthens reconstruction
    after expansion while preserving the small streaming-state contract.
    """

    return build_band_sfc_net_npu_system(
        n_fft=n_fft,
        hop_length=hop_length,
        fs=fs,
        n_src=n_src,
        n_chan=n_chan,
        preset=preset,
        query_type=query_type,
        transport=transport,
        n_bands=n_bands,
        channels=channels,
        num_stages=num_stages,
        time_kernel=time_kernel,
        freq_kernel=freq_kernel,
        dilation_cycle=tuple(dilation_cycle) if dilation_cycle is not None else None,
        routing_normalization=routing_normalization,
        use_attn=use_attn,
        attn_window=attn_window,
        num_heads=num_heads,
        head_dim=head_dim,
        pooled_mixer_hidden=pooled_mixer_hidden,
        pooled_mixer_hidden_schedule=tuple(pooled_mixer_hidden_schedule)
        if pooled_mixer_hidden_schedule is not None
        else None,
        encoder_capacity_mixer_hidden=encoder_capacity_mixer_hidden,
        encoder_capacity_mixer_layers=encoder_capacity_mixer_layers,
        decoder_capacity_mixer_hidden=decoder_capacity_mixer_hidden,
        decoder_capacity_mixer_layers=decoder_capacity_mixer_layers,
        stage_type=stage_type,
        cnb_kernel=cnb_kernel,
        cnb_dilation_schedule=tuple(cnb_dilation_schedule) if cnb_dilation_schedule is not None else None,
        band_spec_type=band_spec_type,
        low_freq_hz=low_freq_hz,
        low_freq_band_fraction=low_freq_band_fraction,
        overlap_factor=overlap_factor,
        low_freq_overlap_factor=low_freq_overlap_factor,
        bin_frequencies_hz=bin_frequencies_hz,
        loco_expansion=loco_expansion,
        loco_ffn_expansion=loco_ffn_expansion,
        loco_time_kernel=loco_time_kernel,
        loco_band_kernel=loco_band_kernel,
        loco_time_dilation=loco_time_dilation,
        residual_head=residual_head,
        scaling=scaling,
        freq_preprocess_enabled=freq_preprocess_enabled,
        freq_preprocess_keep_bins=freq_preprocess_keep_bins,
        freq_preprocess_target_bins=freq_preprocess_target_bins,
        freq_preprocess_mode=freq_preprocess_mode,
        dc_bypass_enabled=dc_bypass_enabled,
        dc_policy=dc_policy,
        pcen_preprocess_enabled=pcen_preprocess_enabled,
        pcen_smooth_coef=pcen_smooth_coef,
        pcen_alpha=pcen_alpha,
        pcen_delta=pcen_delta,
        pcen_root=pcen_root,
        pcen_eps=pcen_eps,
        pcen_gain_floor=pcen_gain_floor,
        pcen_gain_ceiling=pcen_gain_ceiling,
        css_segment_size=css_segment_size,
        css_shift_size=css_shift_size,
        css_batch_size=css_batch_size,
    )


def build_hierarchical_sfc_ffi_lite_system(
    *,
    n_fft: int,
    hop_length: int,
    fs: int,
    n_src: int = 3,
    n_chan: int = 1,
    pre_bands: int = 128,
    mid_bands: int = 96,
    bottleneck_bands: int = 48,
    d_model: int = 20,
    pre_layers: int = 0,
    mid_layers: int = 1,
    bottleneck_layers: int = 1,
    time_branch_kernel_sizes: Sequence[int] = (3, 3),
    time_branch_dilations: Sequence[int] = (1, 6),
    band_config: str = "musical",
    freq_preprocess_enabled: bool = True,
    freq_preprocess_keep_bins: int | None = 475,
    freq_preprocess_target_bins: int | None = 512,
    freq_preprocess_mode: str = "triangular",
    dc_bypass_enabled: bool = False,
    dc_policy: str = "zero",
    pcen_preprocess_enabled: bool = False,
    pcen_smooth_coef: float = 0.98,
    pcen_alpha: float = 0.5,
    pcen_delta: float = 2.0,
    pcen_root: float = 0.5,
    pcen_eps: float = 1e-6,
    pcen_gain_floor: float = 0.05,
    pcen_gain_ceiling: float = 20.0,
    scaling: bool = False,
    css_segment_size: int = 12,
    css_shift_size: int = 6,
    css_batch_size: int = 1,
):
    """Proposal C: hierarchical SFC-FFI middle-tier student."""

    return build_online_hierarchical_soft_band_parallel_ffi_sfc_system(
        n_fft=n_fft,
        hop_length=hop_length,
        fs=fs,
        pre_bands=pre_bands,
        mid_bands=mid_bands,
        bottleneck_bands=bottleneck_bands,
        band_config=band_config,
        n_src=n_src,
        n_chan=n_chan,
        d_model=d_model,
        pre_layers=pre_layers,
        mid_layers=mid_layers,
        bottleneck_layers=bottleneck_layers,
        time_branch_kernel_sizes=tuple(time_branch_kernel_sizes),
        time_branch_dilations=tuple(time_branch_dilations),
        freq_preprocess_enabled=freq_preprocess_enabled,
        freq_preprocess_keep_bins=freq_preprocess_keep_bins,
        freq_preprocess_target_bins=freq_preprocess_target_bins,
        freq_preprocess_mode=freq_preprocess_mode,
        dc_bypass_enabled=dc_bypass_enabled,
        dc_policy=dc_policy,
        pcen_preprocess_enabled=pcen_preprocess_enabled,
        pcen_smooth_coef=pcen_smooth_coef,
        pcen_alpha=pcen_alpha,
        pcen_delta=pcen_delta,
        pcen_root=pcen_root,
        pcen_eps=pcen_eps,
        pcen_gain_floor=pcen_gain_floor,
        pcen_gain_ceiling=pcen_gain_ceiling,
        scaling=scaling,
        css_segment_size=css_segment_size,
        css_shift_size=css_shift_size,
        css_batch_size=css_batch_size,
    )


def build_edgefusion_sfc_distilled_system(
    *,
    n_fft: int,
    hop_length: int,
    fs: int,
    n_src: int = 3,
    n_chan: int = 1,
    preset: str = "large-v2-hybrid-5m",
    scaling: bool = False,
    freq_preprocess_enabled: bool = True,
    freq_preprocess_keep_bins: int | None = 192,
    freq_preprocess_target_bins: int | None = 257,
    freq_preprocess_mode: str = "triangular",
    dc_bypass_enabled: bool = False,
    dc_policy: str = "zero",
    pcen_preprocess_enabled: bool = False,
    pcen_smooth_coef: float = 0.98,
    pcen_alpha: float = 0.5,
    pcen_delta: float = 2.0,
    pcen_root: float = 0.5,
    pcen_eps: float = 1e-6,
    pcen_gain_floor: float = 0.05,
    pcen_gain_ceiling: float = 20.0,
    chunk_frames: int | None = None,
    detach_state_between_chunks: bool = False,
    css_segment_size: int = 12,
    css_shift_size: int = 6,
    css_batch_size: int = 1,
):
    """Proposal E: strict EdgeFusion student intended for teacher distillation."""

    return build_edge_fusion_npu_system(
        n_fft=n_fft,
        hop_length=hop_length,
        fs=fs,
        n_src=n_src,
        n_chan=n_chan,
        preset=preset,
        scaling=scaling,
        freq_preprocess_enabled=freq_preprocess_enabled,
        freq_preprocess_keep_bins=freq_preprocess_keep_bins,
        freq_preprocess_target_bins=freq_preprocess_target_bins,
        freq_preprocess_mode=freq_preprocess_mode,
        dc_bypass_enabled=dc_bypass_enabled,
        dc_policy=dc_policy,
        pcen_preprocess_enabled=pcen_preprocess_enabled,
        pcen_smooth_coef=pcen_smooth_coef,
        pcen_alpha=pcen_alpha,
        pcen_delta=pcen_delta,
        pcen_root=pcen_root,
        pcen_eps=pcen_eps,
        pcen_gain_floor=pcen_gain_floor,
        pcen_gain_ceiling=pcen_gain_ceiling,
        chunk_frames=chunk_frames,
        detach_state_between_chunks=detach_state_between_chunks,
        css_segment_size=css_segment_size,
        css_shift_size=css_shift_size,
        css_batch_size=css_batch_size,
    )


def build_source_aware_melband_roformer_teacher_system(
    *,
    n_fft: int,
    hop_length: int,
    fs: int,
    n_src: int = 3,
    n_chan: int = 1,
    n_bands: int = 128,
    band_config: str | None = None,
    d_model: int = 192,
    n_layers: int | None = None,
    n_heads: int = 8,
    source_attention_heads: int = 1,
    n_encoder_layers: int = 8,
    n_decoder_layers: int = 4,
    ffn_mult: int = 4,
    dropout: float = 0.1,
    conv_kernel_size: Sequence[int] | int = (5, 5),
    routing_kernel_size: Sequence[int] | int = (3, 5),
    low_freq_hz: float = 1000.0,
    low_freq_band_fraction: float = 0.45,
    overlap_factor: float = 1.5,
    low_freq_overlap_factor: float = 2.0,
    include_logmag_features: bool = True,
    masking: bool = True,
    residual_output: bool = True,
    residual_scale_init: float = 0.05,
    mixture_consistency: bool = True,
    routing_normalization: str = "softmax",
    layer_scale_init: float = 0.1,
    scaling: bool = True,
    css_segment_size: int = 12,
    css_shift_size: int = 6,
    css_batch_size: int = 1,
    online_wrapper: bool = False,
    kernel_size: Sequence[int] | int | None = None,
    causal: bool | None = None,
    freq_preprocess_enabled: bool | None = None,
    freq_preprocess_keep_bins: int | None = None,
    freq_preprocess_target_bins: int | None = None,
    freq_preprocess_mode: str | None = None,
    postprocess_enabled: bool = False,
    postprocess_mixture_consistency: str = "none",
    postprocess_final_mixture_consistency: str = "none",
    postprocess_power_beta: float = 1.0,
    postprocess_power_smoothing: float = 0.0,
    postprocess_wiener_blend: float = 0.0,
    postprocess_wiener_alpha: float = 1.0,
    postprocess_leakage_gate_enabled: bool = False,
    postprocess_leakage_gate_threshold_db: float = 12.0,
    postprocess_leakage_gate_attenuation_db: float = 6.0,
    postprocess_residual_source_index: int | None = None,
    postprocess_misi_iterations: int = 0,
    postprocess_misi_eps: float = 1.0e-8,
    postprocess_eps: float = 1.0e-8,
):
    """Performance-first source-aware MelBand RoFormer teacher."""

    del band_config, n_layers, kernel_size, causal
    del freq_preprocess_enabled, freq_preprocess_keep_bins, freq_preprocess_target_bins, freq_preprocess_mode

    return _build_source_aware_melband_roformer_system(
        n_fft=n_fft,
        hop_length=hop_length,
        fs=fs,
        n_src=n_src,
        n_chan=n_chan,
        n_bands=n_bands,
        d_model=d_model,
        n_heads=n_heads,
        source_attention_heads=source_attention_heads,
        n_encoder_layers=n_encoder_layers,
        n_decoder_layers=n_decoder_layers,
        ffn_mult=ffn_mult,
        dropout=dropout,
        conv_kernel_size=conv_kernel_size,
        routing_kernel_size=routing_kernel_size,
        low_freq_hz=low_freq_hz,
        low_freq_band_fraction=low_freq_band_fraction,
        overlap_factor=overlap_factor,
        low_freq_overlap_factor=low_freq_overlap_factor,
        include_logmag_features=include_logmag_features,
        masking=masking,
        residual_output=residual_output,
        residual_scale_init=residual_scale_init,
        mixture_consistency=mixture_consistency,
        routing_normalization=routing_normalization,
        layer_scale_init=layer_scale_init,
        scaling=scaling,
        css_segment_size=css_segment_size,
        css_shift_size=css_shift_size,
        css_batch_size=css_batch_size,
        online_wrapper=online_wrapper,
        postprocess_enabled=postprocess_enabled,
        postprocess_mixture_consistency=postprocess_mixture_consistency,
        postprocess_final_mixture_consistency=postprocess_final_mixture_consistency,
        postprocess_power_beta=postprocess_power_beta,
        postprocess_power_smoothing=postprocess_power_smoothing,
        postprocess_wiener_blend=postprocess_wiener_blend,
        postprocess_wiener_alpha=postprocess_wiener_alpha,
        postprocess_leakage_gate_enabled=postprocess_leakage_gate_enabled,
        postprocess_leakage_gate_threshold_db=postprocess_leakage_gate_threshold_db,
        postprocess_leakage_gate_attenuation_db=postprocess_leakage_gate_attenuation_db,
        postprocess_residual_source_index=postprocess_residual_source_index,
        postprocess_misi_iterations=postprocess_misi_iterations,
        postprocess_misi_eps=postprocess_misi_eps,
        postprocess_eps=postprocess_eps,
    )


def build_source_aware_melband_roformer_student_npu_system(
    *,
    n_fft: int,
    hop_length: int,
    fs: int,
    n_src: int = 3,
    n_chan: int = 1,
    n_bands: int = 80,
    band_config: str | None = None,
    d_model: int = 40,
    n_layers: int | None = None,
    n_encoder_layers: int = 3,
    n_decoder_layers: int = 3,
    long_branch_layers: int = 1,
    correction_layers: int = 1,
    correction_channels: int = 16,
    encoder_expansion: int = 2,
    decoder_expansion: int = 2,
    decoder_fusion_hidden: int | None = None,
    n_heads: int | None = None,
    source_attention_heads: int | None = None,
    ffn_mult: int | None = None,
    dropout: float | None = None,
    kernel_size: Sequence[int] | int = (3, 3),
    decoder_kernel_size: Sequence[int] | int | None = None,
    conv_kernel_size: Sequence[int] | int | None = None,
    routing_kernel_size: Sequence[int] | int = (1, 3),
    dilation_cycle: Sequence[int] | None = None,
    encoder_dilation_cycle: Sequence[int] | None = (1, 2, 4),
    decoder_dilation_cycle: Sequence[int] | None = (1, 2, 4),
    long_branch_dilation_cycle: Sequence[int] | None = (1, 2, 4),
    low_freq_hz: float = 1000.0,
    low_freq_band_fraction: float = 0.45,
    overlap_factor: float = 1.5,
    low_freq_overlap_factor: float = 2.0,
    include_magnitude_features: bool = True,
    include_logmag_features: bool = False,
    residual_output: bool | None = None,
    residual_scale_init: float | None = None,
    mixture_consistency: bool = True,
    routing_normalization: str = "softmax",
    layer_scale_init: float | None = None,
    causal: bool = True,
    masking: bool = True,
    freq_preprocess_enabled: bool = True,
    freq_preprocess_keep_bins: int | None = 475,
    freq_preprocess_target_bins: int | None = 512,
    freq_preprocess_mode: str = "triangular",
    dc_bypass_enabled: bool = False,
    dc_policy: str = "zero",
    pcen_preprocess_enabled: bool = False,
    pcen_smooth_coef: float = 0.98,
    pcen_alpha: float = 0.5,
    pcen_delta: float = 2.0,
    pcen_root: float = 0.5,
    pcen_eps: float = 1e-6,
    pcen_gain_floor: float = 0.05,
    pcen_gain_ceiling: float = 20.0,
    scaling: bool = False,
    css_segment_size: int = 12,
    css_shift_size: int = 6,
    css_batch_size: int = 1,
    online_wrapper: bool | None = None,
):
    """Strict NPU student shaped by the source-aware MelBand RoFormer teacher."""

    del band_config, n_heads, source_attention_heads, ffn_mult, dropout
    del residual_output, residual_scale_init, layer_scale_init, online_wrapper
    if n_layers is not None:
        n_encoder_layers = int(n_layers)
    if conv_kernel_size is not None:
        kernel_size = conv_kernel_size
    if dilation_cycle is not None:
        encoder_dilation_cycle = dilation_cycle
        decoder_dilation_cycle = dilation_cycle

    return _build_source_aware_melband_student_sfc_system(
        n_fft=n_fft,
        hop_length=hop_length,
        fs=fs,
        n_src=n_src,
        n_chan=n_chan,
        n_bands=n_bands,
        d_model=d_model,
        n_encoder_layers=n_encoder_layers,
        n_decoder_layers=n_decoder_layers,
        long_branch_layers=long_branch_layers,
        correction_layers=correction_layers,
        correction_channels=correction_channels,
        encoder_expansion=encoder_expansion,
        decoder_expansion=decoder_expansion,
        decoder_fusion_hidden=decoder_fusion_hidden,
        kernel_size=kernel_size,
        decoder_kernel_size=decoder_kernel_size,
        routing_kernel_size=routing_kernel_size,
        encoder_dilation_cycle=encoder_dilation_cycle,
        decoder_dilation_cycle=decoder_dilation_cycle,
        long_branch_dilation_cycle=long_branch_dilation_cycle,
        low_freq_hz=low_freq_hz,
        low_freq_band_fraction=low_freq_band_fraction,
        overlap_factor=overlap_factor,
        low_freq_overlap_factor=low_freq_overlap_factor,
        include_magnitude_features=include_magnitude_features,
        include_logmag_features=include_logmag_features,
        causal=causal,
        masking=masking,
        mixture_consistency=mixture_consistency,
        routing_normalization=routing_normalization,
        freq_preprocess_enabled=freq_preprocess_enabled,
        freq_preprocess_keep_bins=freq_preprocess_keep_bins,
        freq_preprocess_target_bins=freq_preprocess_target_bins,
        freq_preprocess_mode=freq_preprocess_mode,
        dc_bypass_enabled=dc_bypass_enabled,
        dc_policy=dc_policy,
        pcen_preprocess_enabled=pcen_preprocess_enabled,
        pcen_smooth_coef=pcen_smooth_coef,
        pcen_alpha=pcen_alpha,
        pcen_delta=pcen_delta,
        pcen_root=pcen_root,
        pcen_eps=pcen_eps,
        pcen_gain_floor=pcen_gain_floor,
        pcen_gain_ceiling=pcen_gain_ceiling,
        scaling=scaling,
        css_segment_size=css_segment_size,
        css_shift_size=css_shift_size,
        css_batch_size=css_batch_size,
    )


def build_source_aware_melband_loco_cnb_student_npu_system(
    *,
    n_fft: int,
    hop_length: int,
    fs: int,
    n_src: int = 3,
    n_chan: int = 1,
    core_n_src: int | None = None,
    n_bands: int = 56,
    band_config: str | None = None,
    state_channels: int = 36,
    source_channels: int = 48,
    d_model: int | None = None,
    n_loco_layers: int = 4,
    n_source_layers: int = 4,
    n_layers: int | None = None,
    n_decoder_layers: int | None = None,
    source_local_expansion: int = 2,
    source_local_ffn_mult: int = 4,
    source_fusion_hidden: int = 192,
    source_seed_hidden: int = 192,
    expander_hidden: int = 128,
    mask_hidden: int = 160,
    correction_layers: int = 1,
    correction_channels: int = 16,
    correction_kernel_size: Sequence[int] | int = (1, 5),
    routing_kernel_size: Sequence[int] | int = (1, 3),
    kernel_size: Sequence[int] | int | None = None,
    loco_freq_kernel: int = 3,
    cnb_kernel: int = 4,
    cnb_dilation_schedule: Sequence[int] | None = (1, 2, 3),
    cnb_merge_dilations: bool = False,
    cnb_num_heads: int = 4,
    cnb_head_dim: int = 8,
    cnb_attention_enabled: bool = False,
    pooled_mixer_hidden: int = 0,
    pooled_mixer_hidden_schedule: Sequence[int] | None = None,
    loco_expansion: int = 1,
    loco_ffn_expansion: int = 2,
    loco_time_kernel: int = 3,
    loco_band_kernel: int = 3,
    loco_time_dilation: int = 1,
    low_freq_hz: float = 1000.0,
    low_freq_band_fraction: float = 0.45,
    overlap_factor: float = 1.5,
    low_freq_overlap_factor: float = 2.0,
    include_magnitude_features: bool = True,
    include_logmag_features: bool = False,
    causal: bool = True,
    masking: bool = True,
    mixture_consistency: bool = True,
    routing_normalization: str = "softmax",
    norm_type: str = "rms",
    freq_preprocess_enabled: bool = True,
    freq_preprocess_keep_bins: int | None = 475,
    freq_preprocess_target_bins: int | None = 512,
    freq_preprocess_mode: str = "triangular",
    dc_bypass_enabled: bool = False,
    dc_policy: str = "zero",
    pcen_preprocess_enabled: bool = False,
    pcen_smooth_coef: float = 0.98,
    pcen_alpha: float = 0.5,
    pcen_delta: float = 2.0,
    pcen_root: float = 0.5,
    pcen_eps: float = 1e-6,
    pcen_gain_floor: float = 0.05,
    pcen_gain_ceiling: float = 20.0,
    residual_source_enabled: bool = False,
    residual_source_index: int | None = None,
    scaling: bool = False,
    css_segment_size: int = 12,
    css_shift_size: int = 6,
    css_batch_size: int = 1,
    online_wrapper: bool | None = None,
):
    """Source-aware MelBand student with shared Loco-CNB causal memory."""

    del band_config, kernel_size, online_wrapper
    return _build_source_aware_melband_loco_cnb_student_sfc_system(
        n_fft=n_fft,
        hop_length=hop_length,
        fs=fs,
        n_src=n_src,
        n_chan=n_chan,
        core_n_src=core_n_src,
        n_bands=n_bands,
        state_channels=state_channels,
        source_channels=source_channels,
        d_model=d_model,
        n_loco_layers=n_loco_layers,
        n_source_layers=n_source_layers,
        n_layers=n_layers,
        n_decoder_layers=n_decoder_layers,
        source_local_expansion=source_local_expansion,
        source_local_ffn_mult=source_local_ffn_mult,
        source_fusion_hidden=source_fusion_hidden,
        source_seed_hidden=source_seed_hidden,
        expander_hidden=expander_hidden,
        mask_hidden=mask_hidden,
        correction_layers=correction_layers,
        correction_channels=correction_channels,
        correction_kernel_size=correction_kernel_size,
        routing_kernel_size=routing_kernel_size,
        loco_freq_kernel=loco_freq_kernel,
        cnb_kernel=cnb_kernel,
        cnb_dilation_schedule=cnb_dilation_schedule,
        cnb_merge_dilations=cnb_merge_dilations,
        cnb_num_heads=cnb_num_heads,
        cnb_head_dim=cnb_head_dim,
        cnb_attention_enabled=cnb_attention_enabled,
        pooled_mixer_hidden=pooled_mixer_hidden,
        pooled_mixer_hidden_schedule=pooled_mixer_hidden_schedule,
        loco_expansion=loco_expansion,
        loco_ffn_expansion=loco_ffn_expansion,
        loco_time_kernel=loco_time_kernel,
        loco_band_kernel=loco_band_kernel,
        loco_time_dilation=loco_time_dilation,
        low_freq_hz=low_freq_hz,
        low_freq_band_fraction=low_freq_band_fraction,
        overlap_factor=overlap_factor,
        low_freq_overlap_factor=low_freq_overlap_factor,
        include_magnitude_features=include_magnitude_features,
        include_logmag_features=include_logmag_features,
        causal=causal,
        masking=masking,
        mixture_consistency=mixture_consistency,
        routing_normalization=routing_normalization,
        norm_type=norm_type,
        freq_preprocess_enabled=freq_preprocess_enabled,
        freq_preprocess_keep_bins=freq_preprocess_keep_bins,
        freq_preprocess_target_bins=freq_preprocess_target_bins,
        freq_preprocess_mode=freq_preprocess_mode,
        dc_bypass_enabled=dc_bypass_enabled,
        dc_policy=dc_policy,
        pcen_preprocess_enabled=pcen_preprocess_enabled,
        pcen_smooth_coef=pcen_smooth_coef,
        pcen_alpha=pcen_alpha,
        pcen_delta=pcen_delta,
        pcen_root=pcen_root,
        pcen_eps=pcen_eps,
        pcen_gain_floor=pcen_gain_floor,
        pcen_gain_ceiling=pcen_gain_ceiling,
        residual_source_enabled=residual_source_enabled,
        residual_source_index=residual_source_index,
        scaling=scaling,
        css_segment_size=css_segment_size,
        css_shift_size=css_shift_size,
        css_batch_size=css_batch_size,
    )


def build_source_aware_melband_roformer_strong_student_npu_system(
    *,
    n_fft: int,
    hop_length: int,
    fs: int,
    n_src: int = 3,
    n_chan: int = 1,
    n_bands: int = 80,
    band_config: str | None = None,
    d_model: int = 48,
    n_layers: int | None = None,
    n_encoder_layers: int = 2,
    n_source_layers: int = 5,
    n_decoder_layers: int | None = None,
    correction_layers: int = 1,
    encoder_expansion: int = 2,
    encoder_ffn_mult: int = 4,
    source_local_expansion: int = 2,
    source_local_ffn_mult: int = 4,
    source_fusion_hidden: int = 192,
    source_seed_hidden: int = 192,
    expander_hidden: int = 128,
    mask_hidden: int = 192,
    correction_channels: int = 24,
    n_heads: int | None = None,
    source_attention_heads: int | None = None,
    ffn_mult: int | None = None,
    dropout: float | None = None,
    kernel_size: Sequence[int] | int = (3, 5),
    conv_kernel_size: Sequence[int] | int | None = None,
    routing_kernel_size: Sequence[int] | int = (1, 3),
    dilation_cycle: Sequence[int] | None = None,
    encoder_dilation_cycle: Sequence[int] | None = (1, 2),
    low_freq_hz: float = 1000.0,
    low_freq_band_fraction: float = 0.45,
    overlap_factor: float = 1.5,
    low_freq_overlap_factor: float = 2.0,
    include_magnitude_features: bool = True,
    include_logmag_features: bool = False,
    residual_output: bool | None = None,
    residual_scale_init: float | None = None,
    mixture_consistency: bool = True,
    routing_normalization: str = "softmax",
    layer_scale_init: float | None = None,
    causal: bool = True,
    masking: bool = True,
    freq_preprocess_enabled: bool = True,
    freq_preprocess_keep_bins: int | None = 475,
    freq_preprocess_target_bins: int | None = 512,
    freq_preprocess_mode: str = "triangular",
    dc_bypass_enabled: bool = False,
    dc_policy: str = "zero",
    pcen_preprocess_enabled: bool = False,
    pcen_smooth_coef: float = 0.98,
    pcen_alpha: float = 0.5,
    pcen_delta: float = 2.0,
    pcen_root: float = 0.5,
    pcen_eps: float = 1e-6,
    pcen_gain_floor: float = 0.05,
    pcen_gain_ceiling: float = 20.0,
    scaling: bool = False,
    css_segment_size: int = 12,
    css_shift_size: int = 6,
    css_batch_size: int = 1,
    online_wrapper: bool | None = None,
):
    """Handcrafted strong NPU student for RoFormer-teacher distillation."""

    del band_config, n_heads, source_attention_heads, ffn_mult, dropout
    del residual_output, residual_scale_init, layer_scale_init, online_wrapper
    if n_layers is not None:
        n_encoder_layers = int(n_layers)
    if n_decoder_layers is not None:
        n_source_layers = int(n_decoder_layers)
    if conv_kernel_size is not None:
        kernel_size = conv_kernel_size
    if dilation_cycle is not None:
        encoder_dilation_cycle = dilation_cycle

    return _build_source_aware_melband_strong_student_sfc_system(
        n_fft=n_fft,
        hop_length=hop_length,
        fs=fs,
        n_src=n_src,
        n_chan=n_chan,
        n_bands=n_bands,
        d_model=d_model,
        n_encoder_layers=n_encoder_layers,
        n_source_layers=n_source_layers,
        correction_layers=correction_layers,
        encoder_expansion=encoder_expansion,
        encoder_ffn_mult=encoder_ffn_mult,
        source_local_expansion=source_local_expansion,
        source_local_ffn_mult=source_local_ffn_mult,
        source_fusion_hidden=source_fusion_hidden,
        source_seed_hidden=source_seed_hidden,
        expander_hidden=expander_hidden,
        mask_hidden=mask_hidden,
        correction_channels=correction_channels,
        kernel_size=kernel_size,
        routing_kernel_size=routing_kernel_size,
        encoder_dilation_cycle=encoder_dilation_cycle,
        low_freq_hz=low_freq_hz,
        low_freq_band_fraction=low_freq_band_fraction,
        overlap_factor=overlap_factor,
        low_freq_overlap_factor=low_freq_overlap_factor,
        include_magnitude_features=include_magnitude_features,
        include_logmag_features=include_logmag_features,
        causal=causal,
        masking=masking,
        mixture_consistency=mixture_consistency,
        routing_normalization=routing_normalization,
        freq_preprocess_enabled=freq_preprocess_enabled,
        freq_preprocess_keep_bins=freq_preprocess_keep_bins,
        freq_preprocess_target_bins=freq_preprocess_target_bins,
        freq_preprocess_mode=freq_preprocess_mode,
        dc_bypass_enabled=dc_bypass_enabled,
        dc_policy=dc_policy,
        pcen_preprocess_enabled=pcen_preprocess_enabled,
        pcen_smooth_coef=pcen_smooth_coef,
        pcen_alpha=pcen_alpha,
        pcen_delta=pcen_delta,
        pcen_root=pcen_root,
        pcen_eps=pcen_eps,
        pcen_gain_floor=pcen_gain_floor,
        pcen_gain_ceiling=pcen_gain_ceiling,
        scaling=scaling,
        css_segment_size=css_segment_size,
        css_shift_size=css_shift_size,
        css_batch_size=css_batch_size,
    )


def build_sparse_unet_mel_sfc_music_system(
    *,
    n_fft: int,
    hop_length: int,
    fs: int,
    n_src: int = 4,
    n_chan: int = 2,
    n_bands: int | None = None,
    band_config: str | None = None,
    d_model: int = 64,
    n_layers: int | None = None,
    branch_bands: Sequence[int] = (24, 32, 24),
    encoder_layers: Sequence[int] = (1, 1),
    bottleneck_layers: int = 2,
    decoder_layers: int = 1,
    fullband_capacity_hidden: int = 8192,
    fullband_capacity_layers: int = 1,
    kernel_size: Sequence[int] | tuple[int, int] = (3, 3),
    routing_kernel_size: Sequence[int] | tuple[int, int] = (1, 3),
    low_cutoff_hz: float = 250.0,
    mid_cutoff_hz: float = 4000.0,
    region_overlap_hz: float = 250.0,
    routing_normalization: str = "softmax",
    causal: bool = True,
    masking: bool = True,
    freq_preprocess_enabled: bool = True,
    freq_preprocess_keep_bins: int | None = 475,
    freq_preprocess_target_bins: int | None = 512,
    freq_preprocess_mode: str = "triangular",
    dc_bypass_enabled: bool = False,
    dc_policy: str = "zero",
    pcen_preprocess_enabled: bool = False,
    pcen_smooth_coef: float = 0.98,
    pcen_alpha: float = 0.5,
    pcen_delta: float = 2.0,
    pcen_root: float = 0.5,
    pcen_eps: float = 1e-6,
    pcen_gain_floor: float = 0.05,
    pcen_gain_ceiling: float = 20.0,
    scaling: bool = False,
    css_segment_size: int = 12,
    css_shift_size: int = 6,
    css_batch_size: int = 1,
):
    """Proposal D: Sparse low/mid/high U-Net over overlapped mel-SFC bands."""

    del n_bands, band_config, n_layers

    return _build_sparse_unet_mel_sfc_system(
        n_fft=n_fft,
        hop_length=hop_length,
        fs=fs,
        n_src=n_src,
        n_chan=n_chan,
        d_model=d_model,
        branch_bands=branch_bands,
        encoder_layers=encoder_layers,
        bottleneck_layers=bottleneck_layers,
        decoder_layers=decoder_layers,
        fullband_capacity_hidden=fullband_capacity_hidden,
        fullband_capacity_layers=fullband_capacity_layers,
        kernel_size=kernel_size,
        routing_kernel_size=routing_kernel_size,
        low_cutoff_hz=low_cutoff_hz,
        mid_cutoff_hz=mid_cutoff_hz,
        region_overlap_hz=region_overlap_hz,
        routing_normalization=routing_normalization,
        causal=causal,
        masking=masking,
        freq_preprocess_enabled=freq_preprocess_enabled,
        freq_preprocess_keep_bins=freq_preprocess_keep_bins,
        freq_preprocess_target_bins=freq_preprocess_target_bins,
        freq_preprocess_mode=freq_preprocess_mode,
        dc_bypass_enabled=dc_bypass_enabled,
        dc_policy=dc_policy,
        pcen_preprocess_enabled=pcen_preprocess_enabled,
        pcen_smooth_coef=pcen_smooth_coef,
        pcen_alpha=pcen_alpha,
        pcen_delta=pcen_delta,
        pcen_root=pcen_root,
        pcen_eps=pcen_eps,
        pcen_gain_floor=pcen_gain_floor,
        pcen_gain_ceiling=pcen_gain_ceiling,
        scaling=scaling,
        css_segment_size=css_segment_size,
        css_shift_size=css_shift_size,
        css_batch_size=css_batch_size,
    )


def build_sfc_sepreformer_multistem_system(
    *,
    n_fft: int,
    hop_length: int,
    fs: int,
    n_src: int = 3,
    n_chan: int = 1,
    n_bands: int = 64,
    band_config: str = "musical",
    d_model: int = 32,
    n_layers: int | None = None,
    n_shared_layers: int = 1,
    n_source_layers: int = 2,
    shared_capacity_hidden: int = 6144,
    shared_capacity_layers: int = 4,
    kernel_size: Sequence[int] | tuple[int, int] = (3, 3),
    routing_kernel_size: Sequence[int] | tuple[int, int] = (1, 3),
    causal: bool = True,
    masking: bool = True,
    routing_normalization: str = "softmax",
    freq_preprocess_enabled: bool = True,
    freq_preprocess_keep_bins: int | None = 475,
    freq_preprocess_target_bins: int | None = 512,
    freq_preprocess_mode: str = "triangular",
    dc_bypass_enabled: bool = False,
    dc_policy: str = "zero",
    pcen_preprocess_enabled: bool = False,
    pcen_smooth_coef: float = 0.98,
    pcen_alpha: float = 0.5,
    pcen_delta: float = 2.0,
    pcen_root: float = 0.5,
    pcen_eps: float = 1e-6,
    pcen_gain_floor: float = 0.05,
    pcen_gain_ceiling: float = 20.0,
    scaling: bool = False,
    css_segment_size: int = 12,
    css_shift_size: int = 6,
    css_batch_size: int = 1,
):
    """Proposal F: SepReformer-style early source split on compressed SFC tokens."""

    del n_layers

    return _build_source_split_sfc_system(
        n_fft=n_fft,
        hop_length=hop_length,
        fs=fs,
        n_src=n_src,
        n_chan=n_chan,
        n_bands=n_bands,
        band_config=band_config,
        d_model=d_model,
        n_shared_layers=n_shared_layers,
        n_source_layers=n_source_layers,
        shared_capacity_hidden=shared_capacity_hidden,
        shared_capacity_layers=shared_capacity_layers,
        kernel_size=kernel_size,
        routing_kernel_size=routing_kernel_size,
        causal=causal,
        masking=masking,
        routing_normalization=routing_normalization,
        freq_preprocess_enabled=freq_preprocess_enabled,
        freq_preprocess_keep_bins=freq_preprocess_keep_bins,
        freq_preprocess_target_bins=freq_preprocess_target_bins,
        freq_preprocess_mode=freq_preprocess_mode,
        dc_bypass_enabled=dc_bypass_enabled,
        dc_policy=dc_policy,
        pcen_preprocess_enabled=pcen_preprocess_enabled,
        pcen_smooth_coef=pcen_smooth_coef,
        pcen_alpha=pcen_alpha,
        pcen_delta=pcen_delta,
        pcen_root=pcen_root,
        pcen_eps=pcen_eps,
        pcen_gain_floor=pcen_gain_floor,
        pcen_gain_ceiling=pcen_gain_ceiling,
        scaling=scaling,
        css_segment_size=css_segment_size,
        css_shift_size=css_shift_size,
        css_batch_size=css_batch_size,
    )


def build_source_aware_residual_sfc_system(
    *,
    n_fft: int,
    hop_length: int,
    fs: int,
    n_src: int = 3,
    n_chan: int = 1,
    n_bands: int = 56,
    band_config: str = "musical",
    d_model: int = 28,
    n_layers: int | None = None,
    n_shared_layers: int = 2,
    n_source_layers: int = 2,
    long_branch_layers: int = 1,
    correction_layers: int = 1,
    correction_channels: int = 12,
    shared_capacity_hidden: int = 8192,
    shared_capacity_layers: int = 4,
    kernel_size: Sequence[int] | tuple[int, int] = (3, 3),
    routing_kernel_size: Sequence[int] | tuple[int, int] = (1, 3),
    dilation_cycle: Sequence[int] | None = (1, 2, 4),
    long_branch_dilation_cycle: Sequence[int] | None = (1, 2, 4),
    causal: bool = True,
    masking: bool = True,
    routing_normalization: str = "softmax",
    freq_preprocess_enabled: bool = True,
    freq_preprocess_keep_bins: int | None = 475,
    freq_preprocess_target_bins: int | None = 512,
    freq_preprocess_mode: str = "triangular",
    dc_bypass_enabled: bool = False,
    dc_policy: str = "zero",
    pcen_preprocess_enabled: bool = False,
    pcen_smooth_coef: float = 0.98,
    pcen_alpha: float = 0.5,
    pcen_delta: float = 2.0,
    pcen_root: float = 0.5,
    pcen_eps: float = 1e-6,
    pcen_gain_floor: float = 0.05,
    pcen_gain_ceiling: float = 20.0,
    scaling: bool = False,
    css_segment_size: int = 12,
    css_shift_size: int = 6,
    css_batch_size: int = 1,
):
    """Source-aware SFC with full-band low-rank residual correction."""

    del n_layers

    return _build_source_aware_residual_sfc_system(
        n_fft=n_fft,
        hop_length=hop_length,
        fs=fs,
        n_src=n_src,
        n_chan=n_chan,
        n_bands=n_bands,
        band_config=band_config,
        d_model=d_model,
        n_shared_layers=n_shared_layers,
        n_source_layers=n_source_layers,
        long_branch_layers=long_branch_layers,
        correction_layers=correction_layers,
        correction_channels=correction_channels,
        shared_capacity_hidden=shared_capacity_hidden,
        shared_capacity_layers=shared_capacity_layers,
        kernel_size=kernel_size,
        routing_kernel_size=routing_kernel_size,
        dilation_cycle=dilation_cycle,
        long_branch_dilation_cycle=long_branch_dilation_cycle,
        causal=causal,
        masking=masking,
        routing_normalization=routing_normalization,
        freq_preprocess_enabled=freq_preprocess_enabled,
        freq_preprocess_keep_bins=freq_preprocess_keep_bins,
        freq_preprocess_target_bins=freq_preprocess_target_bins,
        freq_preprocess_mode=freq_preprocess_mode,
        dc_bypass_enabled=dc_bypass_enabled,
        dc_policy=dc_policy,
        pcen_preprocess_enabled=pcen_preprocess_enabled,
        pcen_smooth_coef=pcen_smooth_coef,
        pcen_alpha=pcen_alpha,
        pcen_delta=pcen_delta,
        pcen_root=pcen_root,
        pcen_eps=pcen_eps,
        pcen_gain_floor=pcen_gain_floor,
        pcen_gain_ceiling=pcen_gain_ceiling,
        scaling=scaling,
        css_segment_size=css_segment_size,
        css_shift_size=css_shift_size,
        css_batch_size=css_batch_size,
    )


def build_sfc_residual_refinement_system(
    *,
    n_fft: int,
    hop_length: int,
    fs: int,
    n_src: int = 3,
    n_chan: int = 1,
    n_bands: int = 64,
    band_config: str = "musical",
    d_model: int = 24,
    n_layers: int = 2,
    refinement_layers: int = 1,
    long_branch_layers: int = 1,
    capacity_mixer_hidden: int = 8192,
    capacity_mixer_layers: int = 4,
    kernel_size: Sequence[int] | tuple[int, int] = (3, 3),
    routing_kernel_size: Sequence[int] | tuple[int, int] = (1, 3),
    dilation_cycle: Sequence[int] | None = (1, 2, 4),
    long_branch_dilation_cycle: Sequence[int] | None = (1, 2, 4),
    causal: bool = True,
    masking: bool = True,
    routing_normalization: str = "softmax",
    freq_preprocess_enabled: bool = True,
    freq_preprocess_keep_bins: int | None = 475,
    freq_preprocess_target_bins: int | None = 512,
    freq_preprocess_mode: str = "triangular",
    dc_bypass_enabled: bool = False,
    dc_policy: str = "zero",
    pcen_preprocess_enabled: bool = False,
    pcen_smooth_coef: float = 0.98,
    pcen_alpha: float = 0.5,
    pcen_delta: float = 2.0,
    pcen_root: float = 0.5,
    pcen_eps: float = 1e-6,
    pcen_gain_floor: float = 0.05,
    pcen_gain_ceiling: float = 20.0,
    scaling: bool = False,
    css_segment_size: int = 12,
    css_shift_size: int = 6,
    css_batch_size: int = 1,
):
    """Proposal G: SFC with Mamba2-lite long branch and residual correction."""

    return _build_residual_refinement_sfc_system(
        n_fft=n_fft,
        hop_length=hop_length,
        fs=fs,
        n_src=n_src,
        n_chan=n_chan,
        n_bands=n_bands,
        band_config=band_config,
        d_model=d_model,
        n_layers=n_layers,
        refinement_layers=refinement_layers,
        long_branch_layers=long_branch_layers,
        capacity_mixer_hidden=capacity_mixer_hidden,
        capacity_mixer_layers=capacity_mixer_layers,
        kernel_size=kernel_size,
        routing_kernel_size=routing_kernel_size,
        dilation_cycle=dilation_cycle,
        long_branch_dilation_cycle=long_branch_dilation_cycle,
        causal=causal,
        masking=masking,
        routing_normalization=routing_normalization,
        freq_preprocess_enabled=freq_preprocess_enabled,
        freq_preprocess_keep_bins=freq_preprocess_keep_bins,
        freq_preprocess_target_bins=freq_preprocess_target_bins,
        freq_preprocess_mode=freq_preprocess_mode,
        dc_bypass_enabled=dc_bypass_enabled,
        dc_policy=dc_policy,
        pcen_preprocess_enabled=pcen_preprocess_enabled,
        pcen_smooth_coef=pcen_smooth_coef,
        pcen_alpha=pcen_alpha,
        pcen_delta=pcen_delta,
        pcen_root=pcen_root,
        pcen_eps=pcen_eps,
        pcen_gain_floor=pcen_gain_floor,
        pcen_gain_ceiling=pcen_gain_ceiling,
        scaling=scaling,
        css_segment_size=css_segment_size,
        css_shift_size=css_shift_size,
        css_batch_size=css_batch_size,
    )


def build_adaptive_mel_locoformer_lite_system(
    *,
    n_fft: int,
    hop_length: int,
    fs: int,
    n_src: int = 3,
    n_chan: int = 1,
    n_bands: int = 80,
    band_config: str | None = None,
    d_model: int = 32,
    n_layers: int = 4,
    kernel_size: Sequence[int] | tuple[int, int] = (3, 3),
    routing_kernel_size: Sequence[int] | tuple[int, int] = (1, 3),
    dilation_cycle: Sequence[int] | None = (1, 2, 1, 2),
    expansion: int = 2,
    ffn_expansion: int = 2,
    capacity_mixer_hidden: int = 6144,
    capacity_mixer_layers: int = 4,
    encoder_capacity_mixer_hidden: int = 0,
    encoder_capacity_mixer_layers: int = 0,
    decoder_capacity_mixer_hidden: int = 0,
    decoder_capacity_mixer_layers: int = 0,
    low_freq_hz: float = 1000.0,
    low_freq_band_fraction: float = 0.45,
    overlap_factor: float = 1.5,
    low_freq_overlap_factor: float = 2.0,
    causal: bool = True,
    masking: bool = True,
    routing_normalization: str = "softmax",
    freq_preprocess_enabled: bool = True,
    freq_preprocess_keep_bins: int | None = 475,
    freq_preprocess_target_bins: int | None = 512,
    freq_preprocess_mode: str = "triangular",
    dc_bypass_enabled: bool = False,
    dc_policy: str = "zero",
    pcen_preprocess_enabled: bool = False,
    pcen_smooth_coef: float = 0.98,
    pcen_alpha: float = 0.5,
    pcen_delta: float = 2.0,
    pcen_root: float = 0.5,
    pcen_eps: float = 1e-6,
    pcen_gain_floor: float = 0.05,
    pcen_gain_ceiling: float = 20.0,
    scaling: bool = False,
    css_segment_size: int = 12,
    css_shift_size: int = 6,
    css_batch_size: int = 1,
):
    """Proposal A student: adaptive mel SFC with NPU-safe Locoformer-lite blocks."""

    del band_config

    return _build_adaptive_mel_locoformer_lite_sfc_system(
        n_fft=n_fft,
        hop_length=hop_length,
        fs=fs,
        n_src=n_src,
        n_chan=n_chan,
        n_bands=n_bands,
        d_model=d_model,
        n_layers=n_layers,
        kernel_size=kernel_size,
        routing_kernel_size=routing_kernel_size,
        dilation_cycle=dilation_cycle,
        expansion=expansion,
        ffn_expansion=ffn_expansion,
        capacity_mixer_hidden=capacity_mixer_hidden,
        capacity_mixer_layers=capacity_mixer_layers,
        encoder_capacity_mixer_hidden=encoder_capacity_mixer_hidden,
        encoder_capacity_mixer_layers=encoder_capacity_mixer_layers,
        decoder_capacity_mixer_hidden=decoder_capacity_mixer_hidden,
        decoder_capacity_mixer_layers=decoder_capacity_mixer_layers,
        low_freq_hz=low_freq_hz,
        low_freq_band_fraction=low_freq_band_fraction,
        overlap_factor=overlap_factor,
        low_freq_overlap_factor=low_freq_overlap_factor,
        causal=causal,
        masking=masking,
        routing_normalization=routing_normalization,
        freq_preprocess_enabled=freq_preprocess_enabled,
        freq_preprocess_keep_bins=freq_preprocess_keep_bins,
        freq_preprocess_target_bins=freq_preprocess_target_bins,
        freq_preprocess_mode=freq_preprocess_mode,
        dc_bypass_enabled=dc_bypass_enabled,
        dc_policy=dc_policy,
        pcen_preprocess_enabled=pcen_preprocess_enabled,
        pcen_smooth_coef=pcen_smooth_coef,
        pcen_alpha=pcen_alpha,
        pcen_delta=pcen_delta,
        pcen_root=pcen_root,
        pcen_eps=pcen_eps,
        pcen_gain_floor=pcen_gain_floor,
        pcen_gain_ceiling=pcen_gain_ceiling,
        scaling=scaling,
        css_segment_size=css_segment_size,
        css_shift_size=css_shift_size,
        css_batch_size=css_batch_size,
    )


def build_sfc_locoformer_conv2d_32b_npu_system(
    *,
    n_fft: int,
    hop_length: int,
    fs: int,
    n_src: int = 3,
    n_chan: int = 1,
    core_n_src: int | None = None,
    band_config: str | None = None,
    n_bands: int = 32,
    d_model: int = 192,
    n_loco_layers: int = 2,
    n_layers: int | None = None,
    kernel_size: Sequence[int] | int = (3, 3),
    routing_kernel_size: Sequence[int] | int = (1, 3),
    dilation_cycle: Sequence[int] | None = (1, 2),
    expansion: int = 2,
    ffn_expansion: int = 4,
    source_head_channels: int = 128,
    source_refine_layers: int = 1,
    source_kernel_size: int = 5,
    real_mask_scale: float = 1.5,
    imag_mask_scale: float = 0.12,
    low_freq_hz: float = 1000.0,
    low_freq_band_fraction: float = 0.45,
    overlap_factor: float = 1.5,
    low_freq_overlap_factor: float = 2.0,
    causal: bool = True,
    masking: bool = True,
    routing_normalization: str = "softmax",
    freq_preprocess_enabled: bool = True,
    freq_preprocess_keep_bins: int | None = 475,
    freq_preprocess_target_bins: int | None = 512,
    freq_preprocess_mode: str = "triangular",
    dc_bypass_enabled: bool = False,
    dc_policy: str = "zero",
    pcen_preprocess_enabled: bool = False,
    pcen_smooth_coef: float = 0.98,
    pcen_alpha: float = 0.5,
    pcen_delta: float = 2.0,
    pcen_root: float = 0.5,
    pcen_eps: float = 1e-6,
    pcen_gain_floor: float = 0.05,
    pcen_gain_ceiling: float = 20.0,
    residual_source_enabled: bool = True,
    residual_source_index: int | None = None,
    scaling: bool = False,
    css_segment_size: int = 12,
    css_shift_size: int = 6,
    css_batch_size: int = 1,
    **unused_inherited_model_kwargs,
):
    """32-band SFC-lite student with a 2-layer Conv2D Locoformer separator."""

    del band_config, unused_inherited_model_kwargs
    if n_layers is not None:
        n_loco_layers = int(n_layers)
    return _build_sfc_locoformer_conv2d_32b_npu_system(
        n_fft=n_fft,
        hop_length=hop_length,
        fs=fs,
        n_src=n_src,
        n_chan=n_chan,
        core_n_src=core_n_src,
        n_bands=n_bands,
        d_model=d_model,
        n_loco_layers=n_loco_layers,
        kernel_size=kernel_size,
        routing_kernel_size=routing_kernel_size,
        dilation_cycle=dilation_cycle,
        expansion=expansion,
        ffn_expansion=ffn_expansion,
        source_head_channels=source_head_channels,
        source_refine_layers=source_refine_layers,
        source_kernel_size=source_kernel_size,
        real_mask_scale=real_mask_scale,
        imag_mask_scale=imag_mask_scale,
        low_freq_hz=low_freq_hz,
        low_freq_band_fraction=low_freq_band_fraction,
        overlap_factor=overlap_factor,
        low_freq_overlap_factor=low_freq_overlap_factor,
        causal=causal,
        masking=masking,
        routing_normalization=routing_normalization,
        freq_preprocess_enabled=freq_preprocess_enabled,
        freq_preprocess_keep_bins=freq_preprocess_keep_bins,
        freq_preprocess_target_bins=freq_preprocess_target_bins,
        freq_preprocess_mode=freq_preprocess_mode,
        dc_bypass_enabled=dc_bypass_enabled,
        dc_policy=dc_policy,
        pcen_preprocess_enabled=pcen_preprocess_enabled,
        pcen_smooth_coef=pcen_smooth_coef,
        pcen_alpha=pcen_alpha,
        pcen_delta=pcen_delta,
        pcen_root=pcen_root,
        pcen_eps=pcen_eps,
        pcen_gain_floor=pcen_gain_floor,
        pcen_gain_ceiling=pcen_gain_ceiling,
        residual_source_enabled=residual_source_enabled,
        residual_source_index=residual_source_index,
        scaling=scaling,
        css_segment_size=css_segment_size,
        css_shift_size=css_shift_size,
        css_batch_size=css_batch_size,
    )


def build_prompted_asymmetric_sfc_unified_system(
    *,
    n_fft: int,
    hop_length: int,
    fs: int,
    n_src: int = 3,
    n_chan: int = 1,
    n_bands: int = 64,
    band_config: str = "musical",
    d_model: int = 32,
    n_layers: int | None = None,
    n_encoder_layers: int = 3,
    n_decoder_layers: int = 1,
    encoder_capacity_hidden: int = 6144,
    encoder_capacity_layers: int = 3,
    source_capacity_hidden: int = 2048,
    source_capacity_layers: int = 1,
    kernel_size: Sequence[int] | tuple[int, int] = (3, 3),
    routing_kernel_size: Sequence[int] | tuple[int, int] = (1, 3),
    prompt_labels: Sequence[str] | None = None,
    causal: bool = True,
    masking: bool = True,
    routing_normalization: str = "softmax",
    freq_preprocess_enabled: bool = True,
    freq_preprocess_keep_bins: int | None = 475,
    freq_preprocess_target_bins: int | None = 512,
    freq_preprocess_mode: str = "triangular",
    dc_bypass_enabled: bool = False,
    dc_policy: str = "zero",
    pcen_preprocess_enabled: bool = False,
    pcen_smooth_coef: float = 0.98,
    pcen_alpha: float = 0.5,
    pcen_delta: float = 2.0,
    pcen_root: float = 0.5,
    pcen_eps: float = 1e-6,
    pcen_gain_floor: float = 0.05,
    pcen_gain_ceiling: float = 20.0,
    scaling: bool = False,
    css_segment_size: int = 12,
    css_shift_size: int = 6,
    css_batch_size: int = 1,
):
    """Proposal D: prompt-conditioned asymmetric SFC with a shared decoder."""

    del n_layers

    return _build_prompted_asymmetric_sfc_system(
        n_fft=n_fft,
        hop_length=hop_length,
        fs=fs,
        n_src=n_src,
        n_chan=n_chan,
        n_bands=n_bands,
        band_config=band_config,
        d_model=d_model,
        n_encoder_layers=n_encoder_layers,
        n_decoder_layers=n_decoder_layers,
        encoder_capacity_hidden=encoder_capacity_hidden,
        encoder_capacity_layers=encoder_capacity_layers,
        source_capacity_hidden=source_capacity_hidden,
        source_capacity_layers=source_capacity_layers,
        kernel_size=kernel_size,
        routing_kernel_size=routing_kernel_size,
        prompt_labels=prompt_labels,
        causal=causal,
        masking=masking,
        routing_normalization=routing_normalization,
        freq_preprocess_enabled=freq_preprocess_enabled,
        freq_preprocess_keep_bins=freq_preprocess_keep_bins,
        freq_preprocess_target_bins=freq_preprocess_target_bins,
        freq_preprocess_mode=freq_preprocess_mode,
        dc_bypass_enabled=dc_bypass_enabled,
        dc_policy=dc_policy,
        pcen_preprocess_enabled=pcen_preprocess_enabled,
        pcen_smooth_coef=pcen_smooth_coef,
        pcen_alpha=pcen_alpha,
        pcen_delta=pcen_delta,
        pcen_root=pcen_root,
        pcen_eps=pcen_eps,
        pcen_gain_floor=pcen_gain_floor,
        pcen_gain_ceiling=pcen_gain_ceiling,
        scaling=scaling,
        css_segment_size=css_segment_size,
        css_shift_size=css_shift_size,
        css_batch_size=css_batch_size,
    )


def build_prompted_asymmetric_sfc_foa_event_query_strong_system(
    *,
    n_fft: int,
    hop_length: int,
    fs: int,
    n_src: int | None = None,
    n_queries: int = 4,
    n_chan: int = 4,
    output_n_chan: int = 1,
    n_event_classes: int = 18,
    n_bands: int = 128,
    band_config: str = "musical",
    d_model: int = 192,
    n_heads: int = 8,
    n_encoder_layers: int = 8,
    n_decoder_layers: int = 4,
    ffn_mult: int = 4,
    dropout: float = 0.1,
    conv_kernel_size: Sequence[int] | int = (5, 5),
    routing_kernel_size: Sequence[int] | tuple[int, int] = (3, 5),
    sfc_query_type: str = "adaptive",
    event_condition_hidden: int | None = None,
    event_condition_mode: str = "probability",
    event_class_labels: Sequence[str] | None = None,
    masking: bool = True,
    residual_output: bool = True,
    routing_normalization: str = "softmax",
    scaling: bool = True,
    css_segment_size: int = 12,
    css_shift_size: int = 6,
    css_batch_size: int = 1,
):
    """Proposal D strong: non-NPU FOA separation conditioned by event class queries."""

    return _build_foa_event_query_prompted_asymmetric_sfc_system(
        n_fft=n_fft,
        hop_length=hop_length,
        fs=fs,
        n_src=n_src,
        n_queries=n_queries,
        n_chan=n_chan,
        output_n_chan=output_n_chan,
        n_event_classes=n_event_classes,
        n_bands=n_bands,
        band_config=band_config,
        d_model=d_model,
        n_heads=n_heads,
        n_encoder_layers=n_encoder_layers,
        n_decoder_layers=n_decoder_layers,
        ffn_mult=ffn_mult,
        dropout=dropout,
        conv_kernel_size=conv_kernel_size,
        routing_kernel_size=routing_kernel_size,
        sfc_query_type=sfc_query_type,
        event_condition_hidden=event_condition_hidden,
        event_condition_mode=event_condition_mode,
        event_class_labels=event_class_labels,
        masking=masking,
        residual_output=residual_output,
        routing_normalization=routing_normalization,
        scaling=scaling,
        css_segment_size=css_segment_size,
        css_shift_size=css_shift_size,
        css_batch_size=css_batch_size,
    )


def build_adaptive_mel_sfc_ablation_system(
    *,
    n_fft: int,
    hop_length: int,
    fs: int,
    n_src: int = 3,
    n_chan: int = 1,
    n_bands: int = 80,
    band_config: str | None = None,
    d_model: int = 24,
    n_layers: int = 6,
    capacity_mixer_hidden: int = 8192,
    capacity_mixer_layers: int = 4,
    kernel_size: Sequence[int] | tuple[int, int] = (3, 3),
    routing_kernel_size: Sequence[int] | tuple[int, int] = (1, 3),
    low_freq_hz: float = 1000.0,
    low_freq_band_fraction: float = 0.45,
    overlap_factor: float = 1.5,
    low_freq_overlap_factor: float = 2.0,
    causal: bool = True,
    masking: bool = True,
    routing_normalization: str = "softmax",
    freq_preprocess_enabled: bool = True,
    freq_preprocess_keep_bins: int | None = 475,
    freq_preprocess_target_bins: int | None = 512,
    freq_preprocess_mode: str = "triangular",
    dc_bypass_enabled: bool = False,
    dc_policy: str = "zero",
    pcen_preprocess_enabled: bool = False,
    pcen_smooth_coef: float = 0.98,
    pcen_alpha: float = 0.5,
    pcen_delta: float = 2.0,
    pcen_root: float = 0.5,
    pcen_eps: float = 1e-6,
    pcen_gain_floor: float = 0.05,
    pcen_gain_ceiling: float = 20.0,
    scaling: bool = False,
    css_segment_size: int = 12,
    css_shift_size: int = 6,
    css_batch_size: int = 1,
):
    """Proposal H: explicit 80-band overlapped/adaptive mel SFC ablation."""

    del band_config

    return _build_adaptive_mel_sfc_system(
        n_fft=n_fft,
        hop_length=hop_length,
        fs=fs,
        n_src=n_src,
        n_chan=n_chan,
        n_bands=n_bands,
        d_model=d_model,
        n_layers=n_layers,
        capacity_mixer_hidden=capacity_mixer_hidden,
        capacity_mixer_layers=capacity_mixer_layers,
        kernel_size=kernel_size,
        routing_kernel_size=routing_kernel_size,
        low_freq_hz=low_freq_hz,
        low_freq_band_fraction=low_freq_band_fraction,
        overlap_factor=overlap_factor,
        low_freq_overlap_factor=low_freq_overlap_factor,
        causal=causal,
        masking=masking,
        routing_normalization=routing_normalization,
        freq_preprocess_enabled=freq_preprocess_enabled,
        freq_preprocess_keep_bins=freq_preprocess_keep_bins,
        freq_preprocess_target_bins=freq_preprocess_target_bins,
        freq_preprocess_mode=freq_preprocess_mode,
        dc_bypass_enabled=dc_bypass_enabled,
        dc_policy=dc_policy,
        pcen_preprocess_enabled=pcen_preprocess_enabled,
        pcen_smooth_coef=pcen_smooth_coef,
        pcen_alpha=pcen_alpha,
        pcen_delta=pcen_delta,
        pcen_root=pcen_root,
        pcen_eps=pcen_eps,
        pcen_gain_floor=pcen_gain_floor,
        pcen_gain_ceiling=pcen_gain_ceiling,
        scaling=scaling,
        css_segment_size=css_segment_size,
        css_shift_size=css_shift_size,
        css_batch_size=css_batch_size,
    )
